id: P872F20DD
initial_creation_type: input
source_metadata:
  title: TYKYN
  language: ug
  volumes:
    fd9092e439e141eba131b3be6ebff8e5:
      title: Complete text
      base_file: Complete text.txt
      work_id: WA9E668C6
  chapter_to_tile: {}
created_at: '2022-03-02T09:14:20.991970'
last_modified_at: '2022-03-02T09:14:20.991980'
